version: '3.9'

services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  elasticsearch:
    image: elasticsearch:7.17.2
    restart: always
    environment:
      - 'discovery.type=single-node'
    ports:
      - 9200:9200
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/api
    ports:
      - 3000:3000
    depends_on:
      - db
      - elasticsearch
volumes:
  postgres:
    driver: local
  elasticsearch:
    driver: local
